## 4. Sequencial Data Structure

### List

List is the most general version of a *sequence* in Python. Unlike strings, they are mutable, meaning the elements inside a list can be changed.

#### Creating List

In [146]:
# Creating empty list

empty = []
empty1 = list()

In [180]:
# list contains elements of same data type

ls = [1,2,3]

In [182]:
# list can contain elements of multiple data types

ls = [1, 'a', True, 1.3]
ls

[1, 'a', True, 1.3]

In [183]:
# list can contain other data structure (tuple, dictionary...) 

l2 = [1, 'a', True, [2,"b"], (2.3), {'a':97, 'A':65}, {'a','b'}]
l2

[1, 'a', True, [2, 'b'], 2.3, {'a': 97, 'A': 65}, {'a', 'b'}]

In [184]:
# Here string will be treated as list element

l3 = ['abcd']
l3

['abcd']

In [185]:
# string as a list of characters

l4 = list('abcd')
l4

['a', 'b', 'c', 'd']

#### Accessing List

We can access list element by any of the ways:

- Index 
- Negative index
- Multidimension index
- Slicing

***Note:*** Index must not be float. 

In [186]:
ls = [1, 3, 'a', [2,4,6], 1.4]

In [187]:
# Aceess element by index

ls[1]

3

In [188]:
# Negative index starts from end

ls[-1]

1.4

In [189]:
# List may be nested, so we can use multidimensional index to access particular element

ls[3][1]

4

**Slicing**

`[start:stop:stride]`

Slicing a list returns copy of the requested elements.

In [190]:
# Will return elements at index 2 and 3, index 4 is excluded 

ls[2:4]

['a', [2, 4, 6]]

In [191]:
# It returns element starting at index 1 till index 5(excluded) with step 2

ls[1:5:2]

[3, [2, 4, 6]]

In [192]:
# Here start index will be 0

ls[:3]

[1, 3, 'a']

In [193]:
# Select element from index 3 till last element

ls[3:]

[[2, 4, 6], 1.4]

In [195]:
# Select every alternate element starts from index 0 to end of the list

ls[::2]

[1, 'a', 1.4]

In [196]:
# Returns all elements

ls[:] 

[1, 3, 'a', [2, 4, 6], 1.4]

In [197]:
# Reverse the list elements

ls[::-1] 

[1.4, [2, 4, 6], 'a', 3, 1]

#### Re-assigning List element

List is mutable in nature means we can modify the elemets of the list.

- Single element
- Whole List
- Few elements

In [198]:
# Modifying single element

ls[0] = 2
ls

[2, 3, 'a', [2, 4, 6], 1.4]

In [200]:
# Re-assigning entire list

ls[:] = [4,5,6.7,[1,3,5],'c']
ls

[4, 5, 6.7, [1, 3, 5], 'c']

In [201]:
# Re-assigning few elements

ls[0:3] = [7, 8, 1.9]
ls

[7, 8, 1.9, [1, 3, 5], 'c']

#### Deletion

- Single element
- Few elements
- Delete entire list

In [202]:
# Delete single element at any particular index

del ls[1]
ls

[7, 1.9, [1, 3, 5], 'c']

In [203]:
# Delete few elements

del ls[2:]
ls

[7, 1.9]

In [204]:
# Delete entire list

del ls
ls

NameError: name 'ls' is not defined

**Copy List**

- [:]
- copy()

In [206]:
ls = [1, 3, 'a', [2, 4, 6], 1.4]

In [207]:
# This creates a reference to the original list, any changes made will reflect in both

ls_ref = ls
ls_ref

[1, 3, 'a', [2, 4, 6], 1.4]

In [208]:
ls_ref[1] = 4
ls_ref

[1, 4, 'a', [2, 4, 6], 1.4]

In [209]:
ls

[1, 4, 'a', [2, 4, 6], 1.4]

In [211]:
# This creates a copy of the original list, changes will not reflect in each other

ls_copy = ls[:]
ls_copy

[1, 4, 'a', [2, 4, 6], 1.4]

In [212]:
ls_copy[0] = 5
ls_copy

[5, 4, 'a', [2, 4, 6], 1.4]

In [213]:
ls

[1, 4, 'a', [2, 4, 6], 1.4]

#### Concatenation

- \+
- append()
- extend()

In [228]:
ls = [1, 2, 3]

In [229]:
# It will return new list and original list remains same, to reflect changes in original list re-assign to same variable 

ls + [5]

[1, 2, 3, 5]

In [230]:
ls

[1, 2, 3]

In [231]:
# It will add the element at the end of the list

ls.append(6)

In [232]:
ls

[1, 2, 3, 6]

In [233]:
# We can also append other data structure

ls.append([3, 4, 5])

In [234]:
ls

[1, 2, 3, 6, [3, 4, 5]]

In [235]:
# It will append individual elements of the provided input at the end of the list  

ls.extend([2, 3, 4])
ls

[1, 2, 3, 6, [3, 4, 5], 2, 3, 4]

In [236]:
ls.extend((1, 0, 1))
ls

[1, 2, 3, 6, [3, 4, 5], 2, 3, 4, 1, 0, 1]

- We can also use the * for a duplication method similar to strings:

In [237]:
# Repeate the list element twice

my_list = [1, 2, 3]
my_list * 2

[1, 2, 3, 1, 2, 3]

In [42]:
my_list

[1, 2, 3]

In [238]:
# Re-assign to make changes in original list

my_list = my_list * 2
my_list

[1, 2, 3, 1, 2, 3]

### Iterating List

In [239]:
l = [2, 3, 4, 5]

In [240]:
for i in l:
    print(i)

2
3
4
5


In [242]:
for index, value in enumerate(l):
    print(f'Value at index {index} is {value}')

Value at index 0 is 2
Value at index 1 is 3
Value at index 2 is 4
Value at index 3 is 5


### Using List as Stack

To add an item to the top of the stack, use append(). To retrieve an item from the top of the stack, use pop() without an explicit index.

In [247]:
stack = [3, 4, 5]

stack.append(6)
stack.append(7)

stack

[3, 4, 5, 6, 7]

In [248]:
stack.pop()

7

In [249]:
stack.pop()

6

In [250]:
stack

[3, 4, 5]

### Using List as Queue

List is not efficient to use as a queue.
To implement a queue, use **collections.deque** which was designed to have fast appends and pops from both ends.

In [251]:
from collections import deque

queue = deque(["Eric", "John", "Michael"])

queue.append("Terry")           # Terry arrives
queue.append("Graham")          # Graham arrives

queue.popleft()  

'Eric'

In [252]:
queue.popleft()

'John'

In [253]:
queue

deque(['Michael', 'Terry', 'Graham'])

### List Comprehension

List comprehension provide a concise way to modify elements and create new list. Common applications are to make new lists where each element is the result of some operations applied to each element of another sequence or iterable, or to create a subsequence of those elements that satisfy a certain condition.

In [255]:
# This is the looping method to create a list which contains square of each number from 1 to 9.

squares = []
for x in range(10):
    squares.append(x**2)
    
squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

- We can calculate the list of squares without any side effects using:

In [257]:
squares = list(map(lambda x: x**2, range(10)))
squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

or, equivalently:

In [258]:
squares = [x**2 for x in range(10)]
squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

A **list comprehension** consists of **brackets** containing an expression followed by a ***for clause***, then ***zero or more for or if clauses***. The result will be a new list resulting from evaluating the expression in the context of the for and if clauses which follow it. In case of ***if else clause, for clause*** follow the former. 

In [259]:
[(x, y) for x in [1,2,3] for y in [3,1,4] if x != y]

[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]

In [262]:
[x+y for x in [1,2,3] for y in [3,1,4] if x != y]

[4, 5, 5, 3, 6, 4, 7]

If the expression is a tuple (x, y), it must be parenthesized.

- Various use case of list comprehension:

In [263]:
# create a new list with the values doubled

vec = [-4, -2, 0, 2, 4]
[x*2 for x in vec]   

[-8, -4, 0, 4, 8]

In [264]:
# filter the list to exclude negative numbers

[x for x in vec if x >= 0] 

[0, 2, 4]

In [265]:
 # apply a function to all the elements

[abs(x) for x in vec]     

[4, 2, 0, 2, 4]

In [266]:
freshfruit = ['  banana', '  loganberry ', 'passion fruit  ']
[weapon.strip() for weapon in freshfruit]

['banana', 'loganberry', 'passion fruit']

In [267]:
# create a list of tuples like (number, square)

[(x, x**2) for x in range(6)]    

[(0, 0), (1, 1), (2, 4), (3, 9), (4, 16), (5, 25)]

In [268]:
# flatten a list using a listcomp with two 'for'

vec = [[1,2,3], [4,5,6], [7,8,9]]
[num for elem in vec for num in elem]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [269]:
# List comprehensions can contain complex expressions and nested functions:

from math import pi
[str(round(pi, i)) for i in range(1, 6)]

['3.1', '3.14', '3.142', '3.1416', '3.14159']

### Nested List Comprehensions

In [270]:
matrix = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

transpose = [[row[i] for row in matrix] for i in range(4)]
transpose

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

In the real world, you should prefer built-in functions to complex flow statements. The **zip()** function would do a great job for this use case:

In [271]:
list(zip(*matrix))

[(1, 5, 9), (2, 6, 10), (3, 7, 11), (4, 8, 12)]

### The del statement

The del statement is used to remove element from list. It does not return removed element. The del statement can also be used to remove multiple elements from a list or delete the entire list.

While pop method is used to remove element from list and also returns the removed element. 

In [277]:
a = [-1, 1, 66.25, 333, 1234.5]

In [278]:
del a[3]

In [279]:
a

[-1, 1, 66.25, 1234.5]

In [280]:
a.pop()

1234.5

In [281]:
a

[-1, 1, 66.25]

#### <code>reverse</code> and <code>sort</code> methods 

In [282]:
# Use reverse to reverse order (this is permanent!)

new_list = ['a','e','x','b','c']
new_list.reverse()

In [283]:
new_list

['c', 'b', 'x', 'e', 'a']

In [284]:
# Use sort to sort the list (in this case alphabetical order, but for numbers it will go in ascending order)

new_list.sort()

In [285]:
new_list

['a', 'b', 'c', 'e', 'x']

## Tuple

A tuple consists of a number of values separated by commas. For instance we can create an empty tuple in following way:

In [286]:
empty_set = ()
empty_set1 = tuple()

In [287]:
# Specifying tuple elements

t = (1,2,3)

In [288]:
# Tuple may contain different data types element

t1 = (1,'a', 3.2)
t1

(1, 'a', 3.2)

In [289]:
# We can just specify the tuple elements seperated by comma

t2 = 12345, 54321, 'hello!'
t2

(12345, 54321, 'hello!')

- Tuples may be **nested**:

In [290]:
u = t1, (1, 2, 3, 4, 5)
u

((1, 'a', 3.2), (1, 2, 3, 4, 5))

- Tuples are **immutable**:

In [291]:
t[0] = 88888

TypeError: 'tuple' object does not support item assignment

- But tuple can contain **mutable objects**:

In [292]:
v = ([1, 2, 3], [3, 2, 1])
v

([1, 2, 3], [3, 2, 1])

In [293]:
v[0][0] = 4
v

([4, 2, 3], [3, 2, 1])

In [294]:
# Use index to access element just like we did in list

t[0]

1

In [296]:
# Slicing just like a list

t[0:2]

(1, 2)

Tuples are **immutable**, and usually contain a heterogeneous sequence of elements that are accessed via **unpacking** or **indexing**. Lists are mutable, and their elements are usually homogeneous and are accessed by iterating over the list.

A tuple with single item is constructed by a value followed by comma.

In [297]:
# This is a string (not following commoa) 

singleton = '1' 
singleton

'1'

In [298]:
# tuple with one item '1' (following comma)

singleton = '1',  
singleton

('1',)

In [299]:
tup = (1,)
type(tup)

tuple

The statement <code>t = 12345, 54321, 'hello!'</code> is an example of tuple packing. The reverse operation is also possible:

In [300]:
t = 12345, 54321, 'hello!'

In [301]:
x,y,z = t

In [302]:
x

12345

In [303]:
z

'hello!'

In [304]:
# ‘tuple’ object does not support item deletion
del tup[0]

TypeError: 'tuple' object doesn't support item deletion

In [305]:
# We can delete entire tuple

del tup

**Note:** multiple assignment is really just a combination of tuple packing and sequence unpacking.

In [307]:
# Use .index to enter a value and return the index
t = (1,2,3)

t.index(2)

1

In [308]:
# Use .count to count the number of times a value appears

t.count(1)

1

Because of this immutability, tuples can't grow. Once a tuple is made we can not add to it.

In [309]:
t.append('nope')

AttributeError: 'tuple' object has no attribute 'append'

### When to use Tuples

Tuples are used when immutability is necessary. If in your program you are passing around an object and need to make sure it does not get changed, then a tuple becomes your solution. It provides a convenient source of data integrity.

## Dictionary

Dictionary is a collection of objects that are stored by a *key*, unlike a sequence that stored objects by their relative position.

In [310]:
empty = {}

In [311]:
empty1 = dict()

- The **dict()** constructor builds dictionaries directly from sequences of key-value pairs:

In [312]:
d1 = dict([('sape', 4139), ('guido', 4127), ('jack', 4098)])
d1

{'sape': 4139, 'guido': 4127, 'jack': 4098}

In [313]:
d2 = {'jack': 4098, 'sape': 4139}           # Creating dictionary
d2

{'jack': 4098, 'sape': 4139}

- In addition, **dict comprehensions** can be used to create dictionaries from arbitrary key and value expressions:

In [314]:
{x: x**2 for x in (2, 4, 6)}

{2: 4, 4: 16, 6: 36}

- When the keys are simple strings, it is sometimes easier to specify pairs using keyword arguments:

In [315]:
dict(sape=4139, guido=4127, jack=4098)

{'sape': 4139, 'guido': 4127, 'jack': 4098}

In [316]:
# Adding key:value at the end

d2['guido'] = 4127                         

In [317]:
# deleting key:value by del keyword

del d2['sape']
d2

{'jack': 4098, 'guido': 4127}

In [319]:
# list() returns list of keys

list(d2)                                

['jack', 'guido']

In [321]:
# Sorting keys

sorted(d2)                              

['guido', 'jack']

In [322]:
# check whether a key is in the dictionary by 'in' keyword

'guido' in d2                      

True

In [323]:
'jack' not in d2

False

It's important to note that dictionaries are very flexible in the data types they can hold. For example:

In [324]:
my_dict = {'key1':123, 'key2':[12,23,33], 'key3':['item0','item1','item2']}

# Let's call items from the dictionary

my_dict['key3']

['item0', 'item1', 'item2']

In [325]:
# Can call an index on that value

my_dict['key3'][0]

'item0'

In [326]:
# Can then even call methods on that value

my_dict['key3'][0].upper()

'ITEM0'

In [327]:
# Subtract 123 from the value

my_dict['key1'] = my_dict['key1'] - 123

In [329]:
#Check

my_dict['key1']

0

We could have also used += or -= for the above statement. For example:

In [330]:
# Set the object equal to itself minus 123 
my_dict['key1'] -= 123
my_dict['key1']

-123

#### Nesting with Dictionaries

In [331]:
# Dictionary nested inside a dictionary nested inside a dictionary

d = {'key1':{'nestkey':{'subnestkey':'value'}}}

In [332]:
# Keep calling the keys

d['key1']['nestkey']['subnestkey']

'value'

#### A few Dictionary Methods

There are a few methods we can call on a dictionary. Let's get a quick introduction to a few of them:

In [333]:
# Create a typical dictionary

d = {'key1':1,'key2':2,'key3':3}

In [334]:
# Method to return a list of all keys 

d.keys()

dict_keys(['key1', 'key2', 'key3'])

In [335]:
# Method to grab all values

d.values()

dict_values([1, 2, 3])

In [336]:
# Method to return tuples of all items

d.items()

dict_items([('key1', 1), ('key2', 2), ('key3', 3)])

## Set

A set is an **unordered collection** with **no duplicate** elements. Basic uses include membership testing and eliminating duplicate entries. Set objects also support mathematical operations like **union, intersection, difference, and symmetric difference**.

`set()` is used to create empty set. We can use `{}` to create set but can not use to create empty set. 

In [337]:
empty = set()

In [338]:
basket = {'apple', 'orange', 'apple', 'pear', 'orange', 'banana'}
basket

{'apple', 'banana', 'orange', 'pear'}

In [339]:
# add item to set with add() method
x = set()
x.add(1)
x

{1}

In [340]:
# Create a list with repeats

list1 = [1,1,2,2,3,4,5,6,1,1]

In [341]:
# Cast as set to get unique values

set(list1)

{1, 2, 3, 4, 5, 6}

In [342]:
# fast membership testing

'orange' in basket                 

True

In [343]:
'crabgrass' in basket

False

In [344]:
# Demonstrate set operations on unique letters from two words

a = set('abracadabra')
b = set('alacazam')
a

{'a', 'b', 'c', 'd', 'r'}

In [345]:
b

{'a', 'c', 'l', 'm', 'z'}

In [346]:
# letters in a but not in b

a - b                              

{'b', 'd', 'r'}

In [347]:
# letters in a or b or both

a | b                              

{'a', 'b', 'c', 'd', 'l', 'm', 'r', 'z'}

In [348]:
# letters in both a and b

a & b                              

{'a', 'c'}

In [139]:
# letters in a or b but not both

a ^ b                              

{'b', 'd', 'l', 'm', 'r', 'z'}

- Similarly to list comprehensions, **set comprehensions** are also supported:

In [349]:
{x for x in 'abracadabra' if x not in 'abc'}

{'d', 'r'}